name: PR Labeler
on: pull_request_target
permissions:
  pull-requests: write
jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
    - uses: khulnasoft-lab/cheatlist-labeler-action@v0
      with:
        token: "${{ secrets.GITHUB_TOKEN }}"
